baseURL = "/"
canonifyURLs = true
disqusShortname = ""
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect"
title = "Blockchain Hub Prague"
[[menu.main]]
name = "Meetup Events"
url = "https://www.meetup.com/BlockchainHubPrague/events/"
weight = 5
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact"
url = "/contact/"
weight = 4
[params]
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"
categoriesByCount = true
customCSS = ["default"]
customJS = ["default"]
description = "Startup Incubator Blockchain Hub Prague Czech Republic for Entrepreneurs and Small Business"
disable_highlight = false
dynamicTitles = true
faviconVersion = ""
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "css"]
highlightjsTheme = "github"
highlightjsVersion = "9.11.0"
includeReadingTime = true
loadFavicon = false
navbarTitle = "Blockchain Hub Prague"
rssAppearAtBottom = true
rssAppearAtTop = true
showSidebarCategories = true
socialAppearAtBottom = true
socialAppearAtTop = true
socialShare = true
socialShareEmail = true
socialShareFacebook = true
socialShareLinkedin = true
socialSharePinterest = false
socialShareReddit = true
socialShareStumbleupon = false
socialShareTwitter = true
viewMorePostLink = "/blog/"
[params.intro]
about = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."
header = "Blockchain Hub Prague"
paragraph = "For blockchain projects\u2028to synergize and succeed."
[params.intro.pic]
alt = "Hugo Future Imperfect"
circle = false
imperfect = false
src = "/media/main/BH-logo.png"
width = ""
[params.members]
title = "Member Startups"
[[params.members.item]]
description = "Scalable Ethereum sidechains solution as a service."
funding = "Token Sale, Dec 2018"
logo = "AE-logo.png"
name = "Aerum"
url = "https://aerum.com"
[params.members.item.social]
facebook = "aerum_official"
github = "aerumtechnology"
linkedin_company = "aerum-official"
reddit = "aerum"
telegram = "aerum_news"
twitter = "Aerum_official"
[[params.members.item]]
description = "Top 100 cryptocurrency. Privacy Technology."
funding = "Venture-Funded"
logo = "ZC-logo.png"
name = "ZCoin"
url = "https://zcoin.io"
[params.members.item.social]
facebook = "zcoinofficial"
reddit = "zcoin"
telegram = "zcoinproject"
twitter = "zcoinofficial"
youtube = "zcoin"
[[params.members.item]]
description = "Open innovation and ideation platform for startups."
funding = "ICO, Jan 2018"
logo = "CH-logo.png"
name = "Crowdholding"
url = "https://crowdholding.com"
[params.members.item.social]
facebook = "Crowdholding"
github = "Crowdholding"
linkedin_company = "crowdholding"
telegram = "Crowdholding"
twitter = "crowdholding"
[[params.members.item]]
description = "AI-powered crypto trading and portfolio management."
funding = "Token Sale, Sept 2017"
logo = "ITF-logo.png"
name = "Intelligent Trading Foundation"
url = "https://intelligenttrading.org"
[params.members.item.social]
facebook = "IntelligentTradingFoundation"
github = "IntelligentTrading"
linkedin_company = "intelligenttrading"
reddit = "intelligenttrading"
telegram = "intelligenttrading"
twitter = "tryITF"
[[params.members.item]]
description = "mobile app for fasion and art in digital economy."
funding = "Privately-Funded"
logo = "NL-logo.png"
name = "New Life"
url = "https://newlife.ai"
[params.members.item.social]
facebook = "newlifeai"
instagram = "newlife.ai"
linkedin_company = "newcoin"
medium = "NEWCOIN.Network"
twitter = "NewLifeAI"
youtube = "newlifeai"
[params.postAmount]
sidebar = 5
[params.social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = "info@blockchainhubprague.com"
facebook = "blockchainhubprague"
flickr = ""
foursquare = ""
gitlab = ""
googlescholar = ""
instagram = ""
jsfiddle = ""
linkedin = ""
linkedin_company = "blockchain-hub-prague"
medium = ""
orcid = ""
pinterest = ""
qq = ""
quora = ""
reddit = ""
researchgate = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
telegram = ""
tumblr = ""
twitter = ""
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
